language: python
python:
  - "3.4.3"
env:
- DJANGO_VERSION=1.9.4
# command to install dependencies
install: "pip install -r requirements.txt"

# command to run server
before_script:
  python stats/manage.py runserver &

script:
  stats/manage.py test stats &
  functional_tests.py
